### ISSUE TITLE
Kész Feladatok!

### ISSUE THREAD

**Issue by PapFe** [Teaching-projects/SZE-MOSZE-2020-Alfak#4]
Felraktuk a kért anyagokat. Mivel lezárásra kerültünk így külön repo-t kezdtünk ahova meghívtunk. Ha bármi kérdésed van vagy valami nem okés kérlek szólj és igyekszünk megoldani a dolgot.

**Comment by hegyhati** [comment]
Lattam, de pls merge-eljetek ide vissza a leforkolt kodot, es itt biraljuk majd el. Tegyetek ra ujra, ha megvan.

**Comment by jlilla1** [comment]
@hegyhati nem tudtunk merge-elni, így a pull request-nél hozzárendeltünk assignee-nak. Töröltük a Feladat2 branchet, minden végső megoldásunk a master2 branchen található.

**Comment by hegyhati** [comment]
Atyaeg, miket kavartok... git-bol van meg mit gyakorolni. Pont az volna a lenyege, hogy ne kelljen ilyenekkel szenvedni, de nezem... 
![image](https://user-images.githubusercontent.com/13832329/102008735-06b3b880-3d33-11eb-9499-e1bd96e526cb.png)
Szoval ha elolvassatok, akkor latjatok, hogyha barmelyikotok ad 1 approve review-t akkor mar be tudott volna menni. 

Gameplay-bol Neo-t hianyoltam, de no, legyen egy kozepes mindenkinek, tovabbi szep napot, vizsgaidoszakot.
